### ISSUE TITLE
Libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by Kamin90** [SeungjunNah/DeepDeblur-PyTorch#48]
I have tried to run the code on my own dataset. While training the code, I got this error:
from . import pypocketfft as pfft
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/KB/anaconda3/lib/python3.7/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-37m-x86_64-linux-gnu.so)

I have installed latest GCC using conda install -c conda-forge gcc=12.1.0, but the error still persists.

**Comment by SeungjunNah** [comment]
It looks like an issue of your conda environment.
Please verify you can import scipy independently from running this repo code.

**Comment by Kamin90** [comment]
Thank you so much for your prompt reply. As I have trained the code on my own dataset, I have replaced Go pro images by images from my own dataset under GOPR0884_*** folders.
These are GOPR0884_*** folders which contain the "sharp" and "blur_gamma"
![1](https://user-images.githubusercontent.com/115360952/194841212-8b8e0027-b4da-44cd-bc32-9313b427cc66.PNG)
es 

Here I'm giving the location of specific folder named "GOPR0884_11_00" folder which contains blur and sharp images in their respective sub-folders.

Blur images: **"Research/dataset/GOPRO_Large/train/GOPR0884_11_00/blur_gamma/oilgasfield733.jpg"**
Sharp images: **"Research/dataset/GOPRO_Large/train/GOPR0884_11_00/sharp/oilgasfield496.jpg"**


But, I'm getting this error:

>  File "main.py", line 67, in <module>
    main()
  File "main.py", line 64, in main
    main_worker(args.rank, args)
  File "main.py", line 15, in main_worker
    loaders = Data(args).get_loader()
  File "/home/DeepDeblur-PyTorch-master/src/data/__init__.py", line 73, in __init__
    self.loaders[mode] = _get_data_loader(mode)
  File "/home/DeepDeblur-PyTorch-master/src/data/__init__.py", line 43, in _get_data_loader
    sampler = RandomSampler(dataset, replacement=False)
  File "/home/DeepDeblur/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 95, in __init__
    raise ValueError("num_samples should be a positive integer "
**ValueError: num_samples should be a positive integer value, but got num_samples=0**

 
Please help to find out why this error has occurred.

**Comment by Kamin90** [comment]
The previous problem has been solved. But I'm getting this error:
The dataset I have used has 3-channels.
> ===> Loading train dataset: GOPRO_Large
===> Loading test dataset: GOPRO_Large
Loss function: 1*L1
Metrics: PSNR,SSIM
===> Initializing trainer
results are saved in ../experiment/2022-10-10_20-10-09/result
[Epoch 1 / lr 1.00e-04]
|                                                      | 0/2940 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 64, in main
    main_worker(args.rank, args)
  File "main.py", line 42, in main_worker
    trainer.train(epoch)
  File "/home/DeepDeblur-PyTorch-master/src/train.py", line 99, in train
    output = self.model(input)
  File "/home/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/DeepDeblur-PyTorch-master/src/model/__init__.py", line 58, in forward
    return self.model.G(input)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/DeepDeblur-PyTorch-master/src/model/MSResNet.py", line 59, in forward
    output_pyramid[s] = self.body_models[s](input_s)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/DeepDeblur-PyTorch-master/src/model/ResNet.py", line 35, in forward
    output = self.body(input)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/home/anaconda3/envs/DeepDeblur/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
**RuntimeError: Given groups=1, weight of size [64, 3, 5, 5], expected input[8, 1, 64, 256] to have 3 channels, but got 1 channels instead**
